# Generated by Django 2.1.4 on 2019-01-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=15)),
                ('fullname', models.TextField(max_length=60)),
                ('email_id', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
            ],
        ),
    ]
