# Generated by Django 2.1.4 on 2019-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=10),
        ),
    ]
