# Generated by Django 2.1.4 on 2019-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20190624_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
