# Generated by Django 2.1.4 on 2019-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20190625_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='RND', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='QA', max_length=25),
            preserve_default=False,
        ),
    ]
